version: '3.6'

services:

  brooke-glen-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile-dev
    volumes:
      - './ui:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=development

  # brooke-glen-api:
  #   build:
  #     context: ./services
  #     dockerfile: Dockerfile-dev
  #   volumes:
  #     - './services:/usr/src/app'
  #   ports:
  #     - 5001:5000
  #   environment:
  #     - FLASK_APP=bg_forms/app.py
  #     - FLASK_ENV=development
  #   depends_on:
  #     - brooke-glen-db

  brooke-glen-db:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
  
volumes:
    postgres-data:
