version: '3.5'

services:

  brooke-glen:
    container_name: brooke-glen-ui-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
     - '3001:3000'
    environment:
      - NODE_ENV=development
